<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-V768SUF" ignored="0" name="Test" tests="1" failures="1" timestamp="2021-01-18T18:21:33 IST" time="0.024" errors="0">
  <testcase name="veriWithInValidCredentials" time="0.0" classname="testcases.LogInTest">
    <failure type="org.testng.TestNGException" message="
Method public void testcases.LogInTest.veriWithInValidCredentials(dataProvider.UserType) throws java.io.IOException requires a @DataProvider named : getUser in class org.testng.annotations.DataProvider">
      <![CDATA[org.testng.TestNGException: 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- veriWithInValidCredentials -->
</testsuite> <!-- Test -->
