<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V768SUF" failures="1" tests="2" name="Test" time="11.872" errors="0" timestamp="2021-01-08T10:47:36 IST">
  <testcase classname="testcases.LogInTest2" name="verifyAttendanceWithValidCredentials" time="5.76"/>
  <testcase classname="testcases.LogInTest" name="verifyAttendanceWithInvalidCredentials" time="4.715">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.LogInTest.verifyAttendanceWithInvalidCredentials(LogInTest.java:14)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyAttendanceWithInvalidCredentials -->
</testsuite> <!-- Test -->
